### ISSUE TITLE
All uids not specified via --map-mount get mapped to uid 65534

### ISSUE THREAD

**Issue by crass** [brauner/mount-idmapped#6]
This illustrates the issue:
```
$ ls -ldn /media/tmp0/{,data,media,nfc}
drwxrwx--x.  29 1000 1000 4096 Jan  6 16:40 /media/tmp0/
drwxrwx--x. 199 1000 1000 8192 May 19 19:07 /media/tmp0/data
drwxrwx---.   7 1023 1023 4096 Oct 22  2018 /media/tmp0/media
drwxrwx---.   3 1027 1027 4096 Jan 14  1970 /media/tmp0/nfc

$ mount-idmapped --map-mount b:1023:1000:6 --map-mount b:1000:999:1 /media/tmp0 /media/tmp1
$ ls -ldn /media/tmp1/{,data,media,nfc}                                                       
drwxrwx--x.  29  999  999 4096 Jan  6 16:40 /media/tmp1/
drwxrwx--x. 199  999  999 8192 May 19 19:07 /media/tmp1/data
drwxrwx---.   7 1000 1000 4096 Oct 22  2018 /media/tmp1/media
drwxrwx---.   3 1004 1004 4096 Jan 14  1970 /media/tmp1/nfc

$ umount /media/tmp1
$ mount-idmapped --map-mount b:1023:1000:1 /media/tmp0 /media/tmp1    
$ ls -ldn /media/tmp1/{,data,media,nfc}
drwxrwx--x.  29 65534 65534 4096 Jan  6 16:40 /media/tmp1/
drwxrwx--x. 199 65534 65534 8192 May 19 19:07 /media/tmp1/data
drwxrwx---.   7  1000  1000 4096 Oct 22  2018 /media/tmp1/media
drwxrwx---.   3 65534 65534 4096 Jan 14  1970 /media/tmp1/nfc
```

The directories that have unmapped uids, which get shown as uid 65534, can not be read either. In contrast, if a uid is explicitly mapped to uid 65534, such a directory can be read from. However directories with mapped uids that reside in directories with unmapped uids can be read from.

Is this expected? I would expect that unspecified uids would get mapped using the identity function. Either way using the uid 65534 for the unmapped uid is misleading. And yes, this isn't an issue with this program, but the kernel. But maybe you could organize a fix, being the author behind the kernel code.
This is on the Ubuntu 5.17 OEM kernel.

**Comment by brauner** [comment]
> Is this expected? I would expect that unspecified uids would get mapped using the identity function. Either way using the uid 65534 for the unmapped uid is misleading. And yes, this isn't an issue with this program, but the kernel. But maybe you could organize a fix, being the author behind the kernel code.
This is on the Ubuntu 5.17 OEM kernel.

Hey yes, this is expected. The last digit `:1` in `--map-mount b:1023:1000:1`  means that you want to only map a single uid/gid. All other uids/gids aren't mapped.

The kernel does represent unmapped uids/gids internally as `-1` but to userspace this is exposed as `65534` aka nobody/nogroup since forever so we cannot change that default.

However, the kernel does expose:
```
/proc/sys/kernel/overflowuid
/proc/sys/kernel/overflowgid
```
which allow you to change the uid/gid that is used to represent the notion that this id isn't mapped.

If you want to map all uids we could expose a command line switch or a special indicator that tells the userspace binary to use the identity mapping for all uids/gids that aren't explicitly specfiied.

But note that the `mount(2)` binary is soon growing support for the creation of idmapped mounts so this binary here will be deprecated.

**Comment by brauner** [comment]
I hope this helps.

**Comment by crass** [comment]
Ok, I suspected s much, thanks for the explanation and the pointer to `/proc/sys/kernel/overflowuid`, which I was unaware of.

> But note that the mount(2) binary is soon growing support for the creation of idmapped mounts so this binary here will be deprecated.

Yes, I saw your [pull request to util-linux](https://github.com/util-linux/util-linux/pull/1661). Thanks for the creating it! However, since those changes aren't in master yet, I'm thinking "soon" could be another 4 years for current Ubuntu LTS 22.04, unfortunately.

> If you want to map all uids we could expose a command line switch or a special indicator that tells the userspace binary to use the identity mapping for all uids/gids that aren't explicitly specfiied.

From the cursory reading of your merge request to util-linux, it looks like `mount` won't have the ability to use the identity map for unmapped uids, correct? Though I don't expect this feature to be implemented in this soon to be depreciated tool, I think it would be useful for the soon to be added feature for `mount`. Since most of the code will largely be the same between the two, if it gets added for mount, it probably wouldn't be much work to add here for those who won't get the new util-linux with that feature for a while.

**Comment by brauner** [comment]
> From the cursory reading of your merge request to util-linux, it looks like mount won't have the ability to use the identity map for unmapped uids, correct? Though I don't expect this feature to be implemented in this soon to be depreciated tool, I think it would be useful for the soon to be added feature for mount. Since most of the code will largely be the same between the two, if it gets added for mount, it probably wouldn't be much work to add here for those who won't get the new util-linux with that feature for a while.

Yeah, we can probably do something like this. I make a note.
